apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  labels: 
    app: cicd
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: {{ .Values.appimage}}
        ports:
        - name: cicd-port
          containerPort: 8080
      
